// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;

#[allow(unused_imports, dead_code)]
pub mod binostr {

    pub enum TagValueOffset {}
    #[derive(Copy, Clone, PartialEq)]

    pub struct TagValue<'a> {
        pub _tab: ::flatbuffers::Table<'a>,
    }

    impl<'a> ::flatbuffers::Follow<'a> for TagValue<'a> {
        type Inner = TagValue<'a>;
        #[inline]
        unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
            Self {
                _tab: unsafe { ::flatbuffers::Table::new(buf, loc) },
            }
        }
    }

    impl<'a> TagValue<'a> {
        pub const VT_TEXT: ::flatbuffers::VOffsetT = 4;
        pub const VT_HEX: ::flatbuffers::VOffsetT = 6;

        #[inline]
        pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
            TagValue { _tab: table }
        }
        #[allow(unused_mut)]
        pub fn create<
            'bldr: 'args,
            'args: 'mut_bldr,
            'mut_bldr,
            A: ::flatbuffers::Allocator + 'bldr,
        >(
            _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
            args: &'args TagValueArgs<'args>,
        ) -> ::flatbuffers::WIPOffset<TagValue<'bldr>> {
            let mut builder = TagValueBuilder::new(_fbb);
            if let Some(x) = args.hex {
                builder.add_hex(x);
            }
            if let Some(x) = args.text {
                builder.add_text(x);
            }
            builder.finish()
        }

        #[inline]
        pub fn text(&self) -> Option<&'a str> {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe {
                self._tab
                    .get::<::flatbuffers::ForwardsUOffset<&str>>(TagValue::VT_TEXT, None)
            }
        }
        #[inline]
        pub fn hex(&self) -> Option<::flatbuffers::Vector<'a, u8>> {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe {
                self._tab
                    .get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, u8>>>(
                        TagValue::VT_HEX,
                        None,
                    )
            }
        }
    }

    impl ::flatbuffers::Verifiable for TagValue<'_> {
        #[inline]
        fn run_verifier(
            v: &mut ::flatbuffers::Verifier,
            pos: usize,
        ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
            v.visit_table(pos)?
                .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("text", Self::VT_TEXT, false)?
                .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, u8>>>(
                    "hex",
                    Self::VT_HEX,
                    false,
                )?
                .finish();
            Ok(())
        }
    }
    pub struct TagValueArgs<'a> {
        pub text: Option<::flatbuffers::WIPOffset<&'a str>>,
        pub hex: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, u8>>>,
    }
    impl<'a> Default for TagValueArgs<'a> {
        #[inline]
        fn default() -> Self {
            TagValueArgs {
                text: None,
                hex: None,
            }
        }
    }

    pub struct TagValueBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
        fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
        start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
    }
    impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> TagValueBuilder<'a, 'b, A> {
        #[inline]
        pub fn add_text(&mut self, text: ::flatbuffers::WIPOffset<&'b str>) {
            self.fbb_
                .push_slot_always::<::flatbuffers::WIPOffset<_>>(TagValue::VT_TEXT, text);
        }
        #[inline]
        pub fn add_hex(&mut self, hex: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b, u8>>) {
            self.fbb_
                .push_slot_always::<::flatbuffers::WIPOffset<_>>(TagValue::VT_HEX, hex);
        }
        #[inline]
        pub fn new(
            _fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
        ) -> TagValueBuilder<'a, 'b, A> {
            let start = _fbb.start_table();
            TagValueBuilder {
                fbb_: _fbb,
                start_: start,
            }
        }
        #[inline]
        pub fn finish(self) -> ::flatbuffers::WIPOffset<TagValue<'a>> {
            let o = self.fbb_.end_table(self.start_);
            ::flatbuffers::WIPOffset::new(o.value())
        }
    }

    impl ::core::fmt::Debug for TagValue<'_> {
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
            let mut ds = f.debug_struct("TagValue");
            ds.field("text", &self.text());
            ds.field("hex", &self.hex());
            ds.finish()
        }
    }
    pub enum TagOffset {}
    #[derive(Copy, Clone, PartialEq)]

    pub struct Tag<'a> {
        pub _tab: ::flatbuffers::Table<'a>,
    }

    impl<'a> ::flatbuffers::Follow<'a> for Tag<'a> {
        type Inner = Tag<'a>;
        #[inline]
        unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
            Self {
                _tab: unsafe { ::flatbuffers::Table::new(buf, loc) },
            }
        }
    }

    impl<'a> Tag<'a> {
        pub const VT_VALUES: ::flatbuffers::VOffsetT = 4;

        #[inline]
        pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
            Tag { _tab: table }
        }
        #[allow(unused_mut)]
        pub fn create<
            'bldr: 'args,
            'args: 'mut_bldr,
            'mut_bldr,
            A: ::flatbuffers::Allocator + 'bldr,
        >(
            _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
            args: &'args TagArgs<'args>,
        ) -> ::flatbuffers::WIPOffset<Tag<'bldr>> {
            let mut builder = TagBuilder::new(_fbb);
            if let Some(x) = args.values {
                builder.add_values(x);
            }
            builder.finish()
        }

        #[inline]
        pub fn values(
            &self,
        ) -> Option<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<TagValue<'a>>>>
        {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe {
                self._tab.get::<::flatbuffers::ForwardsUOffset<
                    ::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<TagValue>>,
                >>(Tag::VT_VALUES, None)
            }
        }
    }

    impl ::flatbuffers::Verifiable for Tag<'_> {
        #[inline]
        fn run_verifier(
            v: &mut ::flatbuffers::Verifier,
            pos: usize,
        ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
            v.visit_table(pos)?
                .visit_field::<::flatbuffers::ForwardsUOffset<
                    ::flatbuffers::Vector<'_, ::flatbuffers::ForwardsUOffset<TagValue>>,
                >>("values", Self::VT_VALUES, false)?
                .finish();
            Ok(())
        }
    }
    pub struct TagArgs<'a> {
        pub values: Option<
            ::flatbuffers::WIPOffset<
                ::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<TagValue<'a>>>,
            >,
        >,
    }
    impl<'a> Default for TagArgs<'a> {
        #[inline]
        fn default() -> Self {
            TagArgs { values: None }
        }
    }

    pub struct TagBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
        fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
        start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
    }
    impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> TagBuilder<'a, 'b, A> {
        #[inline]
        pub fn add_values(
            &mut self,
            values: ::flatbuffers::WIPOffset<
                ::flatbuffers::Vector<'b, ::flatbuffers::ForwardsUOffset<TagValue<'b>>>,
            >,
        ) {
            self.fbb_
                .push_slot_always::<::flatbuffers::WIPOffset<_>>(Tag::VT_VALUES, values);
        }
        #[inline]
        pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> TagBuilder<'a, 'b, A> {
            let start = _fbb.start_table();
            TagBuilder {
                fbb_: _fbb,
                start_: start,
            }
        }
        #[inline]
        pub fn finish(self) -> ::flatbuffers::WIPOffset<Tag<'a>> {
            let o = self.fbb_.end_table(self.start_);
            ::flatbuffers::WIPOffset::new(o.value())
        }
    }

    impl ::core::fmt::Debug for Tag<'_> {
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
            let mut ds = f.debug_struct("Tag");
            ds.field("values", &self.values());
            ds.finish()
        }
    }
    pub enum EventOffset {}
    #[derive(Copy, Clone, PartialEq)]

    pub struct Event<'a> {
        pub _tab: ::flatbuffers::Table<'a>,
    }

    impl<'a> ::flatbuffers::Follow<'a> for Event<'a> {
        type Inner = Event<'a>;
        #[inline]
        unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
            Self {
                _tab: unsafe { ::flatbuffers::Table::new(buf, loc) },
            }
        }
    }

    impl<'a> Event<'a> {
        pub const VT_ID: ::flatbuffers::VOffsetT = 4;
        pub const VT_PUBKEY: ::flatbuffers::VOffsetT = 6;
        pub const VT_CREATED_AT: ::flatbuffers::VOffsetT = 8;
        pub const VT_KIND: ::flatbuffers::VOffsetT = 10;
        pub const VT_TAGS: ::flatbuffers::VOffsetT = 12;
        pub const VT_CONTENT: ::flatbuffers::VOffsetT = 14;
        pub const VT_SIG: ::flatbuffers::VOffsetT = 16;

        #[inline]
        pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
            Event { _tab: table }
        }
        #[allow(unused_mut)]
        pub fn create<
            'bldr: 'args,
            'args: 'mut_bldr,
            'mut_bldr,
            A: ::flatbuffers::Allocator + 'bldr,
        >(
            _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
            args: &'args EventArgs<'args>,
        ) -> ::flatbuffers::WIPOffset<Event<'bldr>> {
            let mut builder = EventBuilder::new(_fbb);
            builder.add_created_at(args.created_at);
            if let Some(x) = args.sig {
                builder.add_sig(x);
            }
            if let Some(x) = args.content {
                builder.add_content(x);
            }
            if let Some(x) = args.tags {
                builder.add_tags(x);
            }
            if let Some(x) = args.pubkey {
                builder.add_pubkey(x);
            }
            if let Some(x) = args.id {
                builder.add_id(x);
            }
            builder.add_kind(args.kind);
            builder.finish()
        }

        #[inline]
        pub fn id(&self) -> ::flatbuffers::Vector<'a, u8> {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe {
                self._tab
                    .get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, u8>>>(
                        Event::VT_ID,
                        None,
                    )
                    .unwrap()
            }
        }
        #[inline]
        pub fn pubkey(&self) -> ::flatbuffers::Vector<'a, u8> {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe {
                self._tab
                    .get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, u8>>>(
                        Event::VT_PUBKEY,
                        None,
                    )
                    .unwrap()
            }
        }
        #[inline]
        pub fn created_at(&self) -> i64 {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe { self._tab.get::<i64>(Event::VT_CREATED_AT, Some(0)).unwrap() }
        }
        #[inline]
        pub fn kind(&self) -> u16 {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe { self._tab.get::<u16>(Event::VT_KIND, Some(0)).unwrap() }
        }
        #[inline]
        pub fn tags(
            &self,
        ) -> Option<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<Tag<'a>>>> {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe {
                self._tab.get::<::flatbuffers::ForwardsUOffset<
                    ::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<Tag>>,
                >>(Event::VT_TAGS, None)
            }
        }
        #[inline]
        pub fn content(&self) -> &'a str {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe {
                self._tab
                    .get::<::flatbuffers::ForwardsUOffset<&str>>(Event::VT_CONTENT, None)
                    .unwrap()
            }
        }
        #[inline]
        pub fn sig(&self) -> ::flatbuffers::Vector<'a, u8> {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe {
                self._tab
                    .get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, u8>>>(
                        Event::VT_SIG,
                        None,
                    )
                    .unwrap()
            }
        }
    }

    impl ::flatbuffers::Verifiable for Event<'_> {
        #[inline]
        fn run_verifier(
            v: &mut ::flatbuffers::Verifier,
            pos: usize,
        ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
            v.visit_table(pos)?
                .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, u8>>>(
                    "id",
                    Self::VT_ID,
                    true,
                )?
                .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, u8>>>(
                    "pubkey",
                    Self::VT_PUBKEY,
                    true,
                )?
                .visit_field::<i64>("created_at", Self::VT_CREATED_AT, false)?
                .visit_field::<u16>("kind", Self::VT_KIND, false)?
                .visit_field::<::flatbuffers::ForwardsUOffset<
                    ::flatbuffers::Vector<'_, ::flatbuffers::ForwardsUOffset<Tag>>,
                >>("tags", Self::VT_TAGS, false)?
                .visit_field::<::flatbuffers::ForwardsUOffset<&str>>(
                    "content",
                    Self::VT_CONTENT,
                    true,
                )?
                .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, u8>>>(
                    "sig",
                    Self::VT_SIG,
                    true,
                )?
                .finish();
            Ok(())
        }
    }
    pub struct EventArgs<'a> {
        pub id: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, u8>>>,
        pub pubkey: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, u8>>>,
        pub created_at: i64,
        pub kind: u16,
        pub tags: Option<
            ::flatbuffers::WIPOffset<
                ::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<Tag<'a>>>,
            >,
        >,
        pub content: Option<::flatbuffers::WIPOffset<&'a str>>,
        pub sig: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, u8>>>,
    }
    impl<'a> Default for EventArgs<'a> {
        #[inline]
        fn default() -> Self {
            EventArgs {
                id: None,     // required field
                pubkey: None, // required field
                created_at: 0,
                kind: 0,
                tags: None,
                content: None, // required field
                sig: None,     // required field
            }
        }
    }

    pub struct EventBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
        fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
        start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
    }
    impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> EventBuilder<'a, 'b, A> {
        #[inline]
        pub fn add_id(&mut self, id: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b, u8>>) {
            self.fbb_
                .push_slot_always::<::flatbuffers::WIPOffset<_>>(Event::VT_ID, id);
        }
        #[inline]
        pub fn add_pubkey(
            &mut self,
            pubkey: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b, u8>>,
        ) {
            self.fbb_
                .push_slot_always::<::flatbuffers::WIPOffset<_>>(Event::VT_PUBKEY, pubkey);
        }
        #[inline]
        pub fn add_created_at(&mut self, created_at: i64) {
            self.fbb_
                .push_slot::<i64>(Event::VT_CREATED_AT, created_at, 0);
        }
        #[inline]
        pub fn add_kind(&mut self, kind: u16) {
            self.fbb_.push_slot::<u16>(Event::VT_KIND, kind, 0);
        }
        #[inline]
        pub fn add_tags(
            &mut self,
            tags: ::flatbuffers::WIPOffset<
                ::flatbuffers::Vector<'b, ::flatbuffers::ForwardsUOffset<Tag<'b>>>,
            >,
        ) {
            self.fbb_
                .push_slot_always::<::flatbuffers::WIPOffset<_>>(Event::VT_TAGS, tags);
        }
        #[inline]
        pub fn add_content(&mut self, content: ::flatbuffers::WIPOffset<&'b str>) {
            self.fbb_
                .push_slot_always::<::flatbuffers::WIPOffset<_>>(Event::VT_CONTENT, content);
        }
        #[inline]
        pub fn add_sig(&mut self, sig: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b, u8>>) {
            self.fbb_
                .push_slot_always::<::flatbuffers::WIPOffset<_>>(Event::VT_SIG, sig);
        }
        #[inline]
        pub fn new(
            _fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
        ) -> EventBuilder<'a, 'b, A> {
            let start = _fbb.start_table();
            EventBuilder {
                fbb_: _fbb,
                start_: start,
            }
        }
        #[inline]
        pub fn finish(self) -> ::flatbuffers::WIPOffset<Event<'a>> {
            let o = self.fbb_.end_table(self.start_);
            self.fbb_.required(o, Event::VT_ID, "id");
            self.fbb_.required(o, Event::VT_PUBKEY, "pubkey");
            self.fbb_.required(o, Event::VT_CONTENT, "content");
            self.fbb_.required(o, Event::VT_SIG, "sig");
            ::flatbuffers::WIPOffset::new(o.value())
        }
    }

    impl ::core::fmt::Debug for Event<'_> {
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
            let mut ds = f.debug_struct("Event");
            ds.field("id", &self.id());
            ds.field("pubkey", &self.pubkey());
            ds.field("created_at", &self.created_at());
            ds.field("kind", &self.kind());
            ds.field("tags", &self.tags());
            ds.field("content", &self.content());
            ds.field("sig", &self.sig());
            ds.finish()
        }
    }
    pub enum EventBatchOffset {}
    #[derive(Copy, Clone, PartialEq)]

    pub struct EventBatch<'a> {
        pub _tab: ::flatbuffers::Table<'a>,
    }

    impl<'a> ::flatbuffers::Follow<'a> for EventBatch<'a> {
        type Inner = EventBatch<'a>;
        #[inline]
        unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
            Self {
                _tab: unsafe { ::flatbuffers::Table::new(buf, loc) },
            }
        }
    }

    impl<'a> EventBatch<'a> {
        pub const VT_EVENTS: ::flatbuffers::VOffsetT = 4;

        #[inline]
        pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
            EventBatch { _tab: table }
        }
        #[allow(unused_mut)]
        pub fn create<
            'bldr: 'args,
            'args: 'mut_bldr,
            'mut_bldr,
            A: ::flatbuffers::Allocator + 'bldr,
        >(
            _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
            args: &'args EventBatchArgs<'args>,
        ) -> ::flatbuffers::WIPOffset<EventBatch<'bldr>> {
            let mut builder = EventBatchBuilder::new(_fbb);
            if let Some(x) = args.events {
                builder.add_events(x);
            }
            builder.finish()
        }

        #[inline]
        pub fn events(
            &self,
        ) -> Option<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<Event<'a>>>> {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe {
                self._tab.get::<::flatbuffers::ForwardsUOffset<
                    ::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<Event>>,
                >>(EventBatch::VT_EVENTS, None)
            }
        }
    }

    impl ::flatbuffers::Verifiable for EventBatch<'_> {
        #[inline]
        fn run_verifier(
            v: &mut ::flatbuffers::Verifier,
            pos: usize,
        ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
            v.visit_table(pos)?
                .visit_field::<::flatbuffers::ForwardsUOffset<
                    ::flatbuffers::Vector<'_, ::flatbuffers::ForwardsUOffset<Event>>,
                >>("events", Self::VT_EVENTS, false)?
                .finish();
            Ok(())
        }
    }
    pub struct EventBatchArgs<'a> {
        pub events: Option<
            ::flatbuffers::WIPOffset<
                ::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<Event<'a>>>,
            >,
        >,
    }
    impl<'a> Default for EventBatchArgs<'a> {
        #[inline]
        fn default() -> Self {
            EventBatchArgs { events: None }
        }
    }

    pub struct EventBatchBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
        fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
        start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
    }
    impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> EventBatchBuilder<'a, 'b, A> {
        #[inline]
        pub fn add_events(
            &mut self,
            events: ::flatbuffers::WIPOffset<
                ::flatbuffers::Vector<'b, ::flatbuffers::ForwardsUOffset<Event<'b>>>,
            >,
        ) {
            self.fbb_
                .push_slot_always::<::flatbuffers::WIPOffset<_>>(EventBatch::VT_EVENTS, events);
        }
        #[inline]
        pub fn new(
            _fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
        ) -> EventBatchBuilder<'a, 'b, A> {
            let start = _fbb.start_table();
            EventBatchBuilder {
                fbb_: _fbb,
                start_: start,
            }
        }
        #[inline]
        pub fn finish(self) -> ::flatbuffers::WIPOffset<EventBatch<'a>> {
            let o = self.fbb_.end_table(self.start_);
            ::flatbuffers::WIPOffset::new(o.value())
        }
    }

    impl ::core::fmt::Debug for EventBatch<'_> {
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
            let mut ds = f.debug_struct("EventBatch");
            ds.field("events", &self.events());
            ds.finish()
        }
    }
    #[inline]
    /// Verifies that a buffer of bytes contains a `Event`
    /// and returns it.
    /// Note that verification is still experimental and may not
    /// catch every error, or be maximally performant. For the
    /// previous, unchecked, behavior use
    /// `root_as_event_unchecked`.
    pub fn root_as_event(buf: &[u8]) -> Result<Event<'_>, ::flatbuffers::InvalidFlatbuffer> {
        ::flatbuffers::root::<Event>(buf)
    }
    #[inline]
    /// Verifies that a buffer of bytes contains a size prefixed
    /// `Event` and returns it.
    /// Note that verification is still experimental and may not
    /// catch every error, or be maximally performant. For the
    /// previous, unchecked, behavior use
    /// `size_prefixed_root_as_event_unchecked`.
    pub fn size_prefixed_root_as_event(
        buf: &[u8],
    ) -> Result<Event<'_>, ::flatbuffers::InvalidFlatbuffer> {
        ::flatbuffers::size_prefixed_root::<Event>(buf)
    }
    #[inline]
    /// Verifies, with the given options, that a buffer of bytes
    /// contains a `Event` and returns it.
    /// Note that verification is still experimental and may not
    /// catch every error, or be maximally performant. For the
    /// previous, unchecked, behavior use
    /// `root_as_event_unchecked`.
    pub fn root_as_event_with_opts<'b, 'o>(
        opts: &'o ::flatbuffers::VerifierOptions,
        buf: &'b [u8],
    ) -> Result<Event<'b>, ::flatbuffers::InvalidFlatbuffer> {
        ::flatbuffers::root_with_opts::<Event<'b>>(opts, buf)
    }
    #[inline]
    /// Verifies, with the given verifier options, that a buffer of
    /// bytes contains a size prefixed `Event` and returns
    /// it. Note that verification is still experimental and may not
    /// catch every error, or be maximally performant. For the
    /// previous, unchecked, behavior use
    /// `root_as_event_unchecked`.
    pub fn size_prefixed_root_as_event_with_opts<'b, 'o>(
        opts: &'o ::flatbuffers::VerifierOptions,
        buf: &'b [u8],
    ) -> Result<Event<'b>, ::flatbuffers::InvalidFlatbuffer> {
        ::flatbuffers::size_prefixed_root_with_opts::<Event<'b>>(opts, buf)
    }
    #[inline]
    /// Assumes, without verification, that a buffer of bytes contains a Event and returns it.
    /// # Safety
    /// Callers must trust the given bytes do indeed contain a valid `Event`.
    pub unsafe fn root_as_event_unchecked(buf: &[u8]) -> Event<'_> {
        unsafe { ::flatbuffers::root_unchecked::<Event>(buf) }
    }
    #[inline]
    /// Assumes, without verification, that a buffer of bytes contains a size prefixed Event and returns it.
    /// # Safety
    /// Callers must trust the given bytes do indeed contain a valid size prefixed `Event`.
    pub unsafe fn size_prefixed_root_as_event_unchecked(buf: &[u8]) -> Event<'_> {
        unsafe { ::flatbuffers::size_prefixed_root_unchecked::<Event>(buf) }
    }
    #[inline]
    pub fn finish_event_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(
        fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
        root: ::flatbuffers::WIPOffset<Event<'a>>,
    ) {
        fbb.finish(root, None);
    }

    #[inline]
    pub fn finish_size_prefixed_event_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(
        fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
        root: ::flatbuffers::WIPOffset<Event<'a>>,
    ) {
        fbb.finish_size_prefixed(root, None);
    }
} // pub mod Binostr
